my_dbt_project:
  target: dev
  outputs:
    dev:
      type: mysql
      server: localhost
      port: 3306
      database: employees  # Ensure this is correct
      schema: dbt_models    # Schema where dbt will create its models
      username: dbt_user
      password: your_password
      ssl_disabled: True
