version: 2

sources:
  - name: employees_source
    schema: employees       # The schema of your source tables
    tables:
      - name: current_dept_emp
      - name: departments
      - name: dept_emp
      - name: dept_emp_latest_date
      - name: dept_manager
      - name: employees
      - name: salaries
      - name: titles
