version: 2

sources:
  - name: employees_source
    database: employees  # The name of the database where your source resides
    schema: employees       # The schema of your source tables
    tables:
      - name: employees
      - name: departments
      - name: salaries
      - name: titles
